name: 'Assets Artifacts'
author: 'Guido Scialfa'
description: 'Upload assets to GitHub Artifacts'
runs:
  using: 'node20'
  main: './dist/index.js'
inputs:
  command:
    description: 'Command to execute'
    default: 'yarn build'
  target-dir:
    description: 'Target directory to upload'
    default: './build'
