name: 'Assets Artifacts'
author: 'Guido Scialfa'
description: 'Upload assets to GitHub Artifacts'
runs:
  using: 'node20'
  main: './dist/index.js'
inputs:
  build-command:
    description: 'The command to run to build the assets'
    required: true
